import TemplatePage from "@/components/TemplatePage";

export const metadata = { title: "Demo: Coming Soon - Pages | Materialize - Bootstrap Dashboard PRO" };

export default function Page() {
  return (
    <TemplatePage
      html={"\r\n    \r\n      \r\n      <noscript><iframe src=\"https://www.googletagmanager.com/ns.html?id=GTM-5J3LMKC\" height=\"0\" width=\"0\" style=\"display: none; visibility: hidden\"></iframe></noscript>\r\n      \r\n    \r\n    <!-- Content -->\r\n\r\n  <!-- We are Coming soon -->\r\n  <div class=\"misc-wrapper\">\r\n    <h4 class=\"mb-2 mx-2\">We are launching soon 🚀</h4>\r\n    <p class=\"mb-6 mx-2\">We're creating something awesome. Please subscribe to get notified when it's ready!</p>\r\n    <form onsubmit=\"return false\">\r\n      <div class=\"mb-0 d-flex gap-4 align-items-center\">\r\n        <input type=\"text\" class=\"form-control form-control-sm\" placeholder=\"Enter your email\" autofocus />\r\n        <button type=\"submit\" class=\"btn btn-primary\">Notify</button>\r\n      </div>\r\n    </form>\r\n    <div class=\"d-flex justify-content-center mt-9\">\r\n      <img src=\"/assets/img/illustrations/misc-coming-soon-object.png\" alt=\"misc-coming-soon\" class=\"img-fluid misc-object d-none d-lg-inline-block\" width=\"170\" />\r\n      <img src=\"/assets/img/illustrations/misc-bg-light.png\" alt=\"misc-coming-soon\" class=\"misc-bg d-none d-lg-inline-block\" data-app-light-img=\"illustrations/misc-bg-light.png\" data-app-dark-img=\"illustrations/misc-bg-dark.png\" />\r\n      <img src=\"/assets/img/illustrations/misc-coming-soon-illustration.png\" alt=\"misc-coming-soon\" class=\"img-fluid z-1\" width=\"190\" />\r\n    </div>\r\n  </div>\r\n  <!-- /We are Coming soon -->\r\n\r\n<!-- / Content -->\r\n\r\n    \r\n      <div class=\"buy-now\">\r\n        <a href=\"https://themeforest.net/item/materialize-material-design-admin-template/11446068\" target=\"_blank\" class=\"btn btn-danger btn-buy-now\">Buy Now</a>\r\n      </div>\r\n    \r\n\r\n    \r\n\r\n    <!-- Core JS -->\r\n    \r\n      <!-- build:js assets/vendor/js/theme.js  -->\r\n      \r\n    \r\n    \r\n      \r\n    \r\n    \r\n    \r\n    \r\n\r\n    \r\n    \r\n\r\n    \r\n      \r\n      \r\n    \r\n\r\n    \r\n      \r\n      \r\n        \r\n        \r\n        \r\n          \r\n        \r\n      \r\n      \r\n    \r\n    <!-- endbuild -->\r\n\r\n    <!-- Vendors JS -->\r\n    \r\n\r\n    <!-- Main JS -->\r\n    \r\n      \r\n    \r\n\r\n    <!-- Page JS -->\r\n    \r\n    \r\n  "}
      css={["/assets/vendor/fonts/iconify-icons.css","/assets/vendor/libs/node-waves/node-waves.css","/assets/vendor/libs/pickr/pickr-themes.css","/assets/vendor/css/core.css","/assets/css/demo.css","/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css","/assets/vendor/css/pages/page-misc.css"]}
      scripts={["/assets/vendor/libs/@algolia/autocomplete-js.js","/assets/vendor/js/helpers.js","/assets/vendor/js/template-customizer.js","/assets/js/config.js","/assets/vendor/libs/jquery/jquery.js","/assets/vendor/libs/popper/popper.js","/assets/vendor/js/bootstrap.js","/assets/vendor/libs/node-waves/node-waves.js","/assets/vendor/libs/@algolia/autocomplete-js.js","/assets/vendor/libs/pickr/pickr.js","/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js","/assets/vendor/libs/hammer/hammer.js","/assets/vendor/libs/i18n/i18n.js","/assets/vendor/js/menu.js","/assets/js/main.js"]}
      inlineScripts={["\r\n        (function (w, d, s, l, i) {\r\n          w[l] = w[l] || [];\r\n          w[l].push({ 'gtm.start': new Date().getTime(), event: 'gtm.js' });\r\n          var f = d.getElementsByTagName(s)[0],\r\n            j = d.createElement(s),\r\n            dl = l != 'dataLayer' ? '&l=' + l : '';\r\n          j.async = true;\r\n          j.src = 'https://www.googletagmanager.com/gtm.js?id=' + i + dl;\r\n          f.parentNode.insertBefore(j, f);\r\n        })(window, document, 'script', 'dataLayer', 'GTM-5J3LMKC');\r\n      "]}
      htmlAttrs={{"lang":"en","class":" layout-wide  customizer-hide","dir":"ltr","data-skin":"default","data-bs-theme":"light","data-assets-path":"/assets/","data-template":"vertical-menu-template-semi-dark"}}
      bodyAttrs={{}}
    />
  );
}
