import TemplatePage from "@/components/TemplatePage";

export const metadata = { title: "Demo: Error - Pages | Materialize - Bootstrap Dashboard PRO" };

export default function Page() {
  return (
    <TemplatePage
      html={"\r\n    \r\n      \r\n      <noscript><iframe src=\"https://www.googletagmanager.com/ns.html?id=GTM-5J3LMKC\" height=\"0\" width=\"0\" style=\"display: none; visibility: hidden\"></iframe></noscript>\r\n      \r\n    \r\n    <!-- Content -->\r\n\r\n  <!-- Error -->\r\n  <div class=\"misc-wrapper\">\r\n    <h1 class=\"mb-2 mx-2\" style=\"font-size: 6rem;line-height: 6rem;\">404</h1>\r\n    <h4 class=\"mb-2\">Page Not Found ⚠️</h4>\r\n    <p class=\"mb-6 mx-2\">we couldn't find the page you are looking for</p>\r\n    <div class=\"d-flex justify-content-center mt-9\">\r\n      <img src=\"/materialize-calendar/assets/img/illustrations/misc-error-object.png\" alt=\"misc-error\" class=\"img-fluid misc-object d-none d-lg-inline-block\" width=\"160\" />\r\n      <img src=\"/materialize-calendar/assets/img/illustrations/misc-bg-light.png\" alt=\"misc-error\" class=\"misc-bg d-none d-lg-inline-block\" data-app-light-img=\"illustrations/misc-bg-light.png\" data-app-dark-img=\"illustrations/misc-bg-dark.png\" />\r\n      <div class=\"d-flex flex-column align-items-center\">\r\n        <img src=\"/materialize-calendar/assets/img/illustrations/misc-error-illustration.png\" alt=\"misc-error\" class=\"img-fluid z-1\" width=\"190\" />\r\n        <div>\r\n          <a href=\"/materialize-calendar/\" class=\"btn btn-primary text-center my-10\">Back to home</a>\r\n        </div>\r\n      </div>\r\n    </div>\r\n  </div>\r\n  <!-- /Error -->\r\n\r\n<!-- / Content -->\r\n\r\n    \r\n      <div class=\"buy-now\">\r\n        <a href=\"https://themeforest.net/item/materialize-material-design-admin-template/11446068\" target=\"_blank\" class=\"btn btn-danger btn-buy-now\">Buy Now</a>\r\n      </div>\r\n    \r\n\r\n    \r\n\r\n    <!-- Core JS -->\r\n    \r\n      <!-- build:js assets/vendor/js/theme.js  -->\r\n      \r\n    \r\n    \r\n      \r\n    \r\n    \r\n    \r\n    \r\n\r\n    \r\n    \r\n\r\n    \r\n      \r\n      \r\n    \r\n\r\n    \r\n      \r\n      \r\n        \r\n        \r\n        \r\n          \r\n        \r\n      \r\n      \r\n    \r\n    <!-- endbuild -->\r\n\r\n    <!-- Vendors JS -->\r\n    \r\n\r\n    <!-- Main JS -->\r\n    \r\n      \r\n    \r\n\r\n    <!-- Page JS -->\r\n    \r\n    \r\n  "}
      css={["/materialize-calendar/assets/vendor/fonts/iconify-icons.css","/materialize-calendar/assets/vendor/libs/node-waves/node-waves.css","/materialize-calendar/assets/vendor/libs/pickr/pickr-themes.css","/materialize-calendar/assets/vendor/css/core.css","/materialize-calendar/assets/css/demo.css","/materialize-calendar/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css","/materialize-calendar/assets/vendor/css/pages/page-misc.css"]}
      scripts={["/materialize-calendar/assets/vendor/libs/@algolia/autocomplete-js.js","/materialize-calendar/assets/vendor/js/helpers.js","/materialize-calendar/assets/vendor/js/template-customizer.js","/materialize-calendar/assets/js/config.js","/materialize-calendar/assets/vendor/libs/jquery/jquery.js","/materialize-calendar/assets/vendor/libs/popper/popper.js","/materialize-calendar/assets/vendor/js/bootstrap.js","/materialize-calendar/assets/vendor/libs/node-waves/node-waves.js","/materialize-calendar/assets/vendor/libs/@algolia/autocomplete-js.js","/materialize-calendar/assets/vendor/libs/pickr/pickr.js","/materialize-calendar/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js","/materialize-calendar/assets/vendor/libs/hammer/hammer.js","/materialize-calendar/assets/vendor/libs/i18n/i18n.js","/materialize-calendar/assets/vendor/js/menu.js","/materialize-calendar/assets/js/main.js"]}
      inlineScripts={["\r\n        (function (w, d, s, l, i) {\r\n          w[l] = w[l] || [];\r\n          w[l].push({ 'gtm.start': new Date().getTime(), event: 'gtm.js' });\r\n          var f = d.getElementsByTagName(s)[0],\r\n            j = d.createElement(s),\r\n            dl = l != 'dataLayer' ? '&l=' + l : '';\r\n          j.async = true;\r\n          j.src = 'https://www.googletagmanager.com/gtm.js?id=' + i + dl;\r\n          f.parentNode.insertBefore(j, f);\r\n        })(window, document, 'script', 'dataLayer', 'GTM-5J3LMKC');\r\n      "]}
      htmlAttrs={{"lang":"en","class":" layout-wide  customizer-hide","dir":"ltr","data-skin":"default","data-bs-theme":"light","data-assets-path":"/assets/","data-template":"vertical-menu-template-semi-dark"}}
      bodyAttrs={{}}
    />
  );
}
